name: push-translations

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Qt lrelease
      run: sudo apt-get install qt5-default qttools5-dev-tools

    - name: Install qgis-plugin-ci
      run: pip3 install qgis-plugin-ci

    - name: Push translations
      run: qgis-plugin-ci push-translation ${{ secrets.TX_TOKEN }}
